name: Node CI

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: npm install, build
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
          npm ci
          npm run generate-texture-source
          npm run generate-texture
          grep -v "assets/" .gitignore > .gitignore.tmp
          rm .gitignore
          mv .gitignore.tmp .gitignore
      # Deploy to local repo
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: ./
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
